# create a list of master files for analysis

In [1]:
import glob
import pandas as pd
import json
import pathlib
import hashlib
import json
import os
import glob
import datetime
# import shutil
import zipfile
ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
ts

'20250812_110921_797218'

In [2]:
d_kikin = "../../dat/kikin/"

In [5]:
zs = glob.glob(d_kikin + "**/*.zip", recursive=True)
zs[:3]

['../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240306.zip',
 '../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240321.zip',
 '../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240329.zip']

文字化けに対応しつつ解凍

In [8]:
for f in zs:
    print(f)
    f_out = f.replace(".zip", "")
    
    with zipfile.ZipFile(f) as z:
        for info in z.infolist():
            # ▼▼▼▼▼ ここから修正 ▼▼▼▼▼
            try:
                # 文字化けを修正しようと試みる
                # cp437でエンコードし直し、本来のcp932でデコードする
                filename = info.filename.encode('cp437').decode('cp932')
            except UnicodeEncodeError:
                # このエラーが出る場合、ファイル名は既にUTF-8などで正しくデコードされている
                # そのため、元のファイル名をそのまま使う
                filename = info.filename
            
            info.filename = filename
            # ▲▲▲▲▲ ここまで修正 ▲▲▲▲▲

            # パス区切り文字を'/'に統一する処理（これは元のままでOK）
            if os.sep != "/" and os.sep in info.filename:
                info.filename = info.filename.replace(os.sep, "/")
            
            z.extract(info, f_out)
    # break

../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240306.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240321.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240329.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240412.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240426.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240517.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240524.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240531.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240621.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240628.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240726.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240801.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240902.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20240906.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20241001.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20241101.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20241108.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20241202.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20241227.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20250303.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20250307.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20250430.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20250602.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/i_kaiteinaiyo_20250801.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/osirase_04.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_20120213.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_20140110.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_20180221.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_h31.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_r01.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_r02.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_r04.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240306.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240321.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240329.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240412.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240426.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240517.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240524.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240531.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240628.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240726.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240801.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240902.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20240906.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20241001.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20241101.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20241108.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20241202.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20241227.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250131.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250214.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250303.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250307.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250430.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250602.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_20250801.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/s_kaiteinaiyo_40.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04.20180221.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04_20120125.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04_20140110.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04_h30.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04_r01.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04_r02.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_002.files/tensuhyo_04_r04.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_04.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_05.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_06.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_07.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_08.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_10.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_11.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_12.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_13.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h22.files/i_kaiteinaiyo_14.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_15.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_16.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_17.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_18.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_19.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_20.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_21.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_22.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_23.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_24.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_25.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_26.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_27.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_28.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_29.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_30.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_31.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_32.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_33.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_34.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_35.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_36.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_37.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_38.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_39.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_40.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h24.files/i_kaiteinaiyo_41.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_42.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_43.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_44.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_45.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_46.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_47.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_48.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_49.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_50.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_51.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_52.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_53.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_54.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_55.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_56.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_57.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_58.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_59.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_60.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_61.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_62.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_63.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h26.files/i_kaiteinaiyo_64.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_65.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_66.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_67.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_68.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_69.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_70.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_71.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_72.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_73.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_74.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_75.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_76.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_77.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_78.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_79.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_80.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_81.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_82.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_83.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_84.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_85.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_86.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_87.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_88.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_89.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_90.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_91.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h28.files/i_kaiteinaiyo_92.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_010523.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_010612.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_010705.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_010906.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300530.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300606.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300626.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300711.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300719.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300803.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_300910.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_301004.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_301206.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_301228.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_310111.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_310206.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_310312.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_310408.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_93.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_94.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_95.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_96.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_97.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_98.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_h30.files/i_kaiteinaiyo_99.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r01.files/i_kaiteinaiyo_011007.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r01.files/i_kaiteinaiyo_011108.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r01.files/i_kaiteinaiyo_011126.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r01.files/i_kaiteinaiyo_011205.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r01.files/i_kaiteinaiyo_020110.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r01.files/i_kaiteinaiyo_020306.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r02.files/i_kaiteinaiyo_20200407.zip
../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_01_r02.files/i_kaiteinaiyo_20200414.zip

In [9]:
fs = glob.glob(d_kikin + "**/*.csv", recursive=True)
fs[:3]

['../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/osirase_04/サンプル/05算定回数テーブル.csv',
 '../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_20120213/tensuhyo_02/01補助マスターテーブル.csv',
 '../../dat/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/ikashika/ikashika_001.files/tensuhyo_02_20120213/tensuhyo_02/02包括テーブル.csv']

In [10]:
def get_meta_dict(fs):
    d_meta = dict()
    for f in fs:
        d_meta[f] = dict()
        with open(f,'rb') as file:
            BinaryData = file.read()
            d_meta[f]["sha256"] = hashlib.sha256(BinaryData).hexdigest()
            d_meta[f]["md5"] = hashlib.md5(BinaryData).hexdigest()

        s = os.path.getsize(f)
        d_meta[f]["size"] = str(s/(2**10)) + "kB"

        t = os.path.getmtime(f)
        d_meta[f]["lastfmodification"] = str(datetime.datetime.fromtimestamp(t))

        t = os.path.getctime(f)
        d_meta[f]["filecreation"] = str(datetime.datetime.fromtimestamp(t))

    return d_meta

ファイルのパス、親フォルダなどを得る関数  
正直この処理は美しくないと思う

In [11]:
def get_file_atr_ds(ds, atr):
    res = []
    for f in ds:
        p = pathlib.Path(f)
        if atr == "name":
            res.append(p.name)
        elif atr == "par":
            res.append(p.parent.name)
        elif atr == "gpar":
            res.append(p.parent.parent.name)
        else:
            res.append("")
    return res

## note
以下の系譜のR0504について、日付情報がルール逸脱。  
美しくない個別処理がある。  
増えるようなら処理を考える。  
www.ssk.or.jp/seikyushiharai/tensuhyo/kihonmasta/kihonmasta_02.files/h-3_ALL2023201_R0504.csv

In [12]:
df = pd.DataFrame({"filepath" : fs}) \
    .assign(filename = lambda df:get_file_atr_ds(df.filepath, "name"))\
    .assign(parent = lambda df:get_file_atr_ds(df.filepath, "par"))\
    .assign(gparent = lambda df:get_file_atr_ds(df.filepath, "gpar")) \
    .assign(bearfile = lambda df:df.filename.str.replace(".csv", "",regex=False)) \
    .assign(timeinfo = lambda df:df.bearfile.str.extract('([0-9R_]*$)')) \
    .assign(prefix = lambda df:df.bearfile.str.replace('([0-9_]*$)', "",regex=True)) \
    .assign(ymdinfo = lambda df:df.timeinfo.str.replace('^_', "",regex=True).str[:8]\
               .str.replace('2023201_$', "20230201",regex=True)) \
    .assign(postfix = lambda df:df.timeinfo.str.replace('^_', "",regex=True).str[8:]) \
    .assign(is_kaitei = lambda df:df.bearfile.str.contains("kaitei")) \
    .assign(ymd = lambda df:pd.to_datetime(df.ymdinfo, errors="coerce"))\
    .assign(next_month_day1 = lambda df:df.ymd + pd.offsets.MonthBegin(1)) \
    .assign(next_month_day2 = lambda df:df.next_month_day1 + datetime.timedelta(days =1))
df.head()
# .query("filepath == '/mnt/d/kikin/www.ssk.or.jp/seikyushiharai/tensuhyo/kihonmasta/kihonmasta_02.files/h-3_ALL2023201_R0504.csv'")\

/tmp/ipykernel_44679/3928411442.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  .assign(ymd = lambda df:pd.to_datetime(df.ymdinfo, errors="coerce"))\

,filepath,filename,parent,gparent,bearfile,timeinfo,prefix,ymdinfo,postfix,is_kaitei,ymd,next_month_day1,next_month_day2
0,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,05算定回数テーブル.csv,サンプル,osirase_04,05算定回数テーブル,,05算定回数テーブル,,,False,NaT,NaT,NaT
1,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,01補助マスターテーブル.csv,tensuhyo_02,tensuhyo_02_20120213,01補助マスターテーブル,,01補助マスターテーブル,,,False,NaT,NaT,NaT
2,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,02包括テーブル.csv,tensuhyo_02,tensuhyo_02_20120213,02包括テーブル,,02包括テーブル,,,False,NaT,NaT,NaT
3,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,03-1背反テーブル1.csv,tensuhyo_02,tensuhyo_02_20120213,03-1背反テーブル1,1,03-1背反テーブル,1,,False,NaT,NaT,NaT
4,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,03-2背反テーブル2.csv,tensuhyo_02,tensuhyo_02_20120213,03-2背反テーブル2,2,03-2背反テーブル,2,,False,NaT,NaT,NaT

In [13]:
df.shape

(1623, 13)

In [14]:
%%time
# l_meta = []
d_meta = get_meta_dict(df.filepath)

df_meta = pd.DataFrame().from_dict(d_meta, orient="index")\
    .reset_index(drop=False)\
    .rename(columns={
    "index":"filepath"
})
df_meta.head()
# for r in df.itertuples():
#     print(r.filepath)

#     l_meta.append(d_meta)

CPU times: user 3.27 s, sys: 2.41 s, total: 5.68 s
Wall time: 54.4 s

,filepath,sha256,md5,size,lastfmodification,filecreation
0,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,890542a2abd7d040ab78783bb838af1c456dcdd54e314e...,59b395aa7c467f838d818cd0bf2580cd,10.673828125kB,2025-08-12 11:21:24.940615,2025-08-12 11:21:24.940615
1,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,38cfc25516491e252aef17f93ef4fa4de0ca64ee093485...,cf29e86e3c71970e1f4f88e1e74f5379,886.939453125kB,2025-08-12 11:21:24.991974,2025-08-12 11:21:24.991974
2,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,2b939f604846452eed5c891b4ad97d2b8d9633aa0d9f06...,70d068ccdf6093f9b24b963bb28062e1,6001.912109375kB,2025-08-12 11:21:25.133478,2025-08-12 11:21:25.133478
3,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,e9abb2b236605c230435dafe08e09bbf93941b402582a8...,9443610957dd09433753eb9230b2e1bf,578.05078125kB,2025-08-12 11:21:25.147316,2025-08-12 11:21:25.147316
4,../../dat/kikin/www.ssk.or.jp/seikyushiharai/t...,92000a77113ec6044414d4f6a325a44463d850db653205...,fcb7bb8a12b2244dc42dffb0ed5ad644,392.81640625kB,2025-08-12 11:21:25.159542,2025-08-12 11:21:25.159542

In [15]:
df_ = pd.merge(df, df_meta, on="filepath")
df_.shape

(1623, 18)

In [29]:
f_x = "./masterfile_{0}.xlsx".format(ts)
f_pk = "./masterfile_{0}.pkl".format(ts)
f_pq = "./masterfile_{0}.parquet".format(ts)
f_x, f_pk, f_pq

('./masterfile_20250812_110921_797218.xlsx',
 './masterfile_20250812_110921_797218.pkl',
 './masterfile_20250812_110921_797218.parquet')

In [30]:
df_.to_excel(f_x)
df_.to_pickle(f_pk)
df_.to_parquet(f_pq)

In [24]:

# today = datetime.datetime.today()
today = datetime.datetime.fromisoformat("2025-07-01")
# start_day = "2019-06-01"
start_day = "2010-01-01"
max_proc_date = 1e+4
# start_day = "2020-06-01"
print(today.date())
df_dt = pd.DataFrame().from_dict({"dt": pd.date_range(start_day, periods=max_proc_date, freq="D")}) \
    .assign(dt_str = lambda df:df.dt.astype(str)) \
    .assign(yy_str = lambda df:df.dt.dt.year.astype(str)) \
    .assign(mm_str = lambda df:df.dt.dt.month.astype(str)) \
    .assign(dd_str = lambda df:df.dt.dt.day.astype(str)) \
    .assign(is_past = lambda df:df.dt < today ) \
    .query("is_past") \
    .sort_values("dt", ascending=True) \
    .reset_index(drop=True)
# df.query("not is_past").head()

2025-07-01

/tmp/ipykernel_44679/4064724768.py:8: FutureWarning: Non-integer 'periods' in pd.date_range, pd.timedelta_range, pd.period_range, and pd.interval_range are deprecated and will raise in a future version.
  df_dt = pd.DataFrame().from_dict({"dt": pd.date_range(start_day, periods=max_proc_date, freq="D")}) \

日付テーブル  
この日付分マスターを作る

In [25]:
df_dt.head()

          dt      dt_str yy_str mm_str dd_str  is_past
0 2010-01-01  2010-01-01   2010      1      1     True
1 2010-01-02  2010-01-02   2010      1      2     True
2 2010-01-03  2010-01-03   2010      1      3     True
3 2010-01-04  2010-01-04   2010      1      4     True
4 2010-01-05  2010-01-05   2010      1      5     True

In [27]:
fdt_x = "./datefile_{0}.xlsx".format(ts)
fdt_pk = "./datefile_{0}.pkl".format(ts)
fdt_pq = "./datefile_{0}.parquet".format(ts)
fdt_x, fdt_pk, fdt_pq

('./datefile_20250812_110921_797218.xlsx',
 './datefile_20250812_110921_797218.pkl',
 './datefile_20250812_110921_797218.parquet')

In [28]:
df_dt.to_excel(fdt_x)
df_dt.to_pickle(fdt_pk)
df_dt.to_parquet(fdt_pq)